---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: sample-metrics-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sample-metrics-app
  template:
    metadata:
      labels:
        app: sample-metrics-app
    spec:
      containers:
      - name: sample-metrics-app
        image: rekulapallyrohith/sample-metrics-app
        ports:
        - containerPort: 5000
        - containerPort: 8000
---
apiVersion: v1
kind: Service
metadata:
  name: sample-metrics-service
spec:
  selector:
    app: sample-metrics-app
  ports:
    - name: http-5000
      protocol: TCP
      port: 5000
      targetPort: 5000
    - name: http-8000
      protocol: TCP
      port: 8000
      targetPort: 8000
---