apiVersion: v1
kind: Pod
metadata: 
  name: mysql
spec: 
  containers:
    - name: mysql
      image: mysql
      env:
        - name: MYSQL_ROOT_PASSWORD
          value: "password"
      ports:
        - containerPort: 3306
  volumes:
    - name: mysql-volume
      persistentVolumeClaim: 
        claimName: mysql-pvc
        readOnly: false