---
apiVersion: v1
kind: Pod
metadata: 
  name: nginx-1
  labels:
    app.kubernetes.io/name: nginx
spec: 
  containers:
    - name: nginx
      image: nginx
      resources:
        limits:
          memory: "128Mi"
          cpu: "500m"
      ports:
        - containerPort: 80
      volumeMounts:
        - mountPath: "/mnt"
          name: mnt-volume
          readOnly: false
  volumes:
    - name: mnt-volume
      persistentVolumeClaim: 
        claimName: test-pvc
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: test-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: nginx-retain
---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata: 
  name: nginx-retain
provisioner: disk.csi.azure.com
reclaimPolicy: Retain
---