
apiVersion: v1
kind: Pod
metadata: 
  name: selectnode-1
spec: 
  nodeSelector:
    env: prod
  containers:
    - name: web
      image: nginx
      resources:
        requests:
          cpu: 100m
          memory: 10M
        limits:
          cpu: 500m
          memory: 128M