
apiVersion: v1
kind: Pod
metadata: 
  name: selectnode1
spec: 
nodeName:
containers:
  - name: web
    image: nginx
    resources:
      requests:
        cpu: 100m
        memory: 10M
      limits:
        cpu: 500m
        memory: 128M

        