apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata: 
  name: qa
rules: 
  - apiGroups: [""]
    resources: ["pods", "services"]
    verbs: ["get", "watch", "list"]
  - apiGroups: ["apps"]
    resources: ["replicasets", "deployments"]
    verbs: ["get", "watch", "list"]