
...
apiVersion: v1
kind: Pod
metadata: 
  name: dual-pod
spec:
  containers:
    - name: first
      image: nginx
    - name: second
      image: alpine
      command:
        - sleep
        - 1d
...