
apiVersion: v1
kind: Pod
metadata:
  name: init
spec:
  containers:
    - name: web
      image: nginx
      resources:
        requests:
          cpu: 100m
          memory: 10M
        limits:
          cpu: 500m
          memory: 128M
  initcontainers:
    - name: cont1
      image: alpine
      args:
        - sleep
        - 5s
    - name: cont2
      image: alpine
      args:
        - sleep
        - 10s