...

apiVersion: v1
kind: Pod
metadata:
  name: myfirst-pod
spec:
  automountServiceAccountToken: false
  containers:
    - name: web1
      image: alpine
      ports:
        - containerPort: 80
    
