apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: basic-cluster
  region: us-west-2
iam:
  withOIDC: true
nodeGroups:
  - name: ng-1
    instanceType: m7i-flex.large
    desiredCapacity: 2
    minSize: 2
    maxSize: 5
addons:
  - name: aws-ebs-csi-driver