
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: qa-rb
  namespace: default
subjects: 
  - kind: User
    name: qa
    apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: Role
  name: qa
  apiGroup: rbac.authorization.k8s.io