apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-deploy
spec:
  minReadySeconds: 5
  replicas: 4
  selector:
    matchLabels:
      app: web
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
  template:
    metadata: 
      labels: 
        app: web
    spec:
      containers:
        - name: web
          image: nginx
          resources:
            requests:
              cpu: "100m"
              memory: 64Mi
            limits:
              cpu: "200m"
              memory: 128Mi
          ports: 
            - name: httpd
              protocol: TCP
              containerPort: 80
          startupProbe:
            initialDelaySeconds: 2
            periodSeconds: 5
            successThreshold: 1
            failureThreshold: 2
            tcpSocket:
              port: 80
          livenessProbe:
            initialDelaySeconds: 2
            periodSeconds: 5
            successThreshold: 1
            failureThreshold: 2
            httpGet:
              path: /
              port: 80
          readinessProbe:
            initialDelaySeconds: 2
            periodSeconds: 5
            successThreshold: 1
            failureThreshold: 2
            httpGet:
              path: /
              port: 80 