
apiVersion: batch/v1
kind: CronJob
metadata: 
  name: cron
spec:
  schedule: "*/5 * * * *"
  jobTemplate: 
    metadata: 
      name: cronjob
    spec: 
      template: 
        metadata:
          labels: 
            app: job
        spec:
          containers:
            - name: worker
              image: alpine
              args:
                - sleep 
                - 30s
          restartPolicy: OnFailure

