apiVersion: v1
kind: Pod
metadata:
  name: cm-pod-demo
spec:
  containers:
    - name: web1
      image: alpine
      command:
        - sleep
        - 1d
      volumeMounts:
        - name: cm-vol
          mountPath: /tools
  volumes:
    - name: cm-vol
      configMap:
        name: mysql-cm