apiVersion: v1
kind: Pod
metadata:
  name: pod-4
  labels:
    app: pod4
spec:
  tolerations:
    - key: ssd 
      value: ultra
      operator: Equal
      effect: NoExecute 
  containers:
    - name: web
      image: nginx
      resources:
        requests:
          cpu: 100m
          memory: 10M
        limits:
          cpu: 500m
          memory: 256M 