apiVersion: v1
kind: Pod
metadata:
  name: vol-demo
spec:
  
  containers:
    - name: web1
      image: alpine
      ports:
        - containerPort: 80
      volumeMounts:
        - name: test-vol
          mountPath: /tools
  volumes:
    - name: test-vol
      emptyDir: