
apiVersion: v1
kind: Pod
metadata:
  name: mysql-fromcreds
  labels: 
    app: web
spec:
  containers:
    - name: mysql-fromcreds
      image: mysql:lts
      ports:
        - containerPort: 3306
      envFrom:
        - secretRef:
            name: mysql-creds
            optional: False