
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: my-ds
spec:
  minReadySeconds: 5
  revisionHistoryLimit:
  selector:
    matchLabels: 
      app: agent
  template:
    metadata:
      labels:
        app: agent
    spec: 
      containers:
        - name: agent
          image: alpine
          args:
            - sleep
            - 1d