apiVersion: v1
kind: Service
metadata:
  name: {{.Values.service.name}}
spec:
  type: {{.Values.service.type}}
  selector:
    app: web
  ports:
    - name: http
      port: {{.Values.service.ports.port}}
      targetPort: {{.Values.service.ports.targetPort}}
      protocol: {{.Values.service.ports.protocol}}