
apiVersion: v1
kind: Pod
metadata: 
  name: mysql
spec: 
  containers:
    - name: mysql
      image: mysql:9
      env:
        - name: MYSQL_ROOT_PASSWORD
          value: "password"
      ports:
        - containerPort: 3306